### PR TITLE
Bug 291546 - Replaced Vector with CopyOnWriteList and Hashtable with

### PR DESCRIPTION
**Pull request by svendiedrichsen**
ConcurrentHashmap

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=291546

**Comment by kratz74** [comment]
We won't merge this diff without Eclipse validation being passed. Also, diff contains full files (end of lines changes) and it can't be applied as it is.

**Comment by svendiedrichsen** [comment]
Thank you very much.

**Comment by kratz74** [comment]
Do you need backport to 2.6? I started with master and will do backport to 2.7 which is quite simple. 2.6 may not match diff so it's another manual work. :(

**Comment by svendiedrichsen** [comment]
I have done the original patch to 2.6 because I'm currently working with Glassfish4/Payara4 which use the 2.6 branch. And if there will be another 2.6 release Payara4 will most likely integrate it. So it would be a nice to have thing if you don't mind porting it back.

**Comment by kratz74** [comment]
Fix is now in master, 2.7 and 2.6 branches. It will be available when 2.6.6 is released.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=291546 for more details.
We'll also integrate it into GlassFish4.

**Comment by svendiedrichsen** [comment]
@kratz74 This is great news. Thank you very much.

**Pull request closed without merging**
